# H2 database in memory (PostgreSQL compatibility mode)
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa

# Flyway
spring.flyway.locations=classpath:db/migration/h2

# Server port
server.port=8090

# Pagination
paginacao.qtd_por_pagina=25

# JWT
jwt.secret=_@HRL&L3tF?Z7ccj4z&L5!nU2B!Rjs3_
jwt.expiration=604800
